// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/companion/recaps/:slug": {
    params: {
      "slug": string;
    };
  };
  "/companion/plans/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/companion/recaps/:slug" | "/companion/plans/:slug";
  };
  "routes/companion.recaps.$slug.tsx": {
    id: "routes/companion.recaps.$slug";
    page: "/companion/recaps/:slug";
  };
  "routes/companion.plans.$slug.tsx": {
    id: "routes/companion.plans.$slug";
    page: "/companion/plans/:slug";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/companion.recaps.$slug": typeof import("./app/routes/companion.recaps.$slug.tsx");
  "routes/companion.plans.$slug": typeof import("./app/routes/companion.plans.$slug.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};
